### ISSUE TITLE
Error while doing poetry run pytest

### ISSUE THREAD

**Issue by Shibu778** [vasp-dev/py4vasp#151]
While doing 'poetry run pytest`, I encountered following error.

```shell
(py4vasp-env) PS <path>\py4vasp> poetry run pytest
Traceback (most recent call last):
  File "<some_path>\.conda\envs\py4vasp_pymatgne\lib\site-packages\requests\compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<some_path>\.conda\envs\py4vasp_pymatgne\lib\site-packages\requests\compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  <some info>
    from poetry.mixology.solutions.providers.python_requirement_solution_provider import (
  <some info>
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
```

**Comment by Shibu778** [comment]
I performed a `pip install chardet` in the environment and it resolved the error.

**Comment by martin-schlipf** [comment]
I cannot reproduce this issue. It seems that this originates from somewhere inside poetry. How did you install poetry? Did you change anything compared to the instructions in the README file?

**Comment by Shibu778** [comment]
I didn't change anything as instructed in the README file. Following is the step, I followed.

1. First created the environment : `conda create --name py4vasp-env python=3.8`
2. Second cloned the project : `git clone https://github.com/vasp-dev/py4vasp.git`
3. Activated the environment: `conda activate py4vasp-env`
4. Installed poetry: `pip install poetry`
5. Went into the clone repository: `cd py4vasp`
6. Did `poetry install`
7. Then did `conda install -c conda-forge mdtraj`
8. Then did `poetry run pytest`

Now it worked. I also couldn't reproduce this, either. 

I figured out that installation of mdtraj with `conda install conda-forge::mdtraj` is causing that error.  It is installing some old package along with some extra package.
1. Brotli (1.0.9) (instead of 1.1.0)
2. charset-normalizer (2.0.4) (instead of 3.3.2)
3. idna (3.4) (instead of 3.6)
4. platformdirs (3.10.0) (instead of 3.11.0)
5. pooch (1.7.0) (instead of 1.8.1)

Extra packages:
1. Bottleneck (1.3.7)
2. mkl-fft (1.3.8)
3. mkl-random (1.2.4)
4. mkl-service (2.4.0)
