### ISSUE TITLE
mpirun parameters

### ISSUE THREAD

**Issue by DeeliN-uno** [vasp-dev/py4vasp#40]
Correct mpirun settings can significantly speed up VASP calculations, there are some common concerns many users have:

- KPAR: set KPAR=number of Kpoint in IBZKPT can achieve maximum speed, but this can not be done BEFORE calculation, because we prepare KPOINTS file instead of IBZKPT for most cases.
- NCORE: set NCORE as high as possible can speed up calculations for most cases, but it's ignored in openMP/MPI hybrid version, which seems to be slower than pure MPI version with high NCORE.
- Modify code with AMD toolchain support, currently we can build and run VASP with AOCC+AOCL toolchain on AMD CPU machine, but to be honest, it performs slower than VASP built with intel oneAPI on AMD CPU machine. 

How can we set KPAR from KPOINTS file (usually use Monkhorst theme to generate K-point grid) before running VASP?

How can we maximize calculation efficiency with openMP/MPI hybrid version?

Is it possible to do some modification to better run VASP on AMD CPU?

**Comment by martin-schlipf** [comment]
Sorry, but these don't seem to be py4vasp issues. You cannot optimize VASP via py4vasp at the current stage. For general VASP questions, we have a separate [support forum](https://vasp.at/forum/). Would you mind taking your questions there, please?
