### ISSUE TITLE
Error is reported when "from py4vasp import Calculation" in jupyter

### ISSUE THREAD

**Issue by xinliang-huang** [vasp-dev/py4vasp#72]
Hello,

I install py4vasp, and then run the command "python - c" import py4vasp; print (py4vasp. __version__) ". It indicates that the installation is successful, but an error is reported when running in jupyter. I don't know why.

After running "from py4vasp import calculation", an error is reported as follows：

Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?c1b71d77-902f-4332-8ace-13b8e8811fb8)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[15], line 1
----> 1 from py4vasp import Calculation

File /work/huangxl/codes/anaconda3/lib/python3.8/site-packages/py4vasp/__init__.py:3
      1 # Copyright © VASP Software GmbH,
      2 # Licensed under the Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
----> 3 from .calculation import Calculation
      4 from py4vasp._third_party.interactive import set_error_handling
      6 __version__ = "0.4.0"

File /work/huangxl/codes/anaconda3/lib/python3.8/site-packages/py4vasp/calculation.py:16
      3 """Provide the tools to manage VASP calculations.
      4 
      5 This is the main user interface if you want to simply investigate the results of VASP
   (...)
     13 >>> calc.structure.print()  # to print the structure in a POSCAR format
     14 """
     15 import inspect
---> 16 import py4vasp.data
     17 import py4vasp.exceptions as exception
     18 import py4vasp.control

File /work/huangxl/codes/anaconda3/lib/python3.8/site-packages/py4vasp/data/__init__.py:33
...
     52 if self._ready:
     53     return
---> 54 super()._ipython_display_(**kwargs)

AttributeError: 'super' object has no attribute '_ipython_display_'

**Comment by martin-schlipf** [comment]
Thank you for reporting this. The issue is caused by a recent upgrade to ipywidgets that [broke the nglview package](nglviewer/nglview#1032). To fix this you can
~~~shell
pip uninstall ipywidgets
pip install ipywidgets==7.7
~~~
