### ISSUE TITLE
search help about py4vasp on Mac jupyter

### ISSUE THREAD

**Issue by billcsu** [vasp-dev/py4vasp#89]
Dear developer,
I encountered a problem when using py4vasp on jupyter installed on Mac OS 10.15, when reading .h5 file, it said there was no access, while this file can be read on Linux jupyter. I dont know why
<img width="1617" alt="image" src="https://github.com/vasp-dev/py4vasp/assets/133481966/d9faa770-249a-4e53-9e8e-2b525ab1d489">

**Comment by martin-schlipf** [comment]
Perhaps you can try the solutions in this thread. In particular the h5debug
Tool and downloading the file again.
https://stackoverflow.com/questions/38089950/error-opening-file-in-h5py-file-signature-not-found

**Comment by billcsu** [comment]
Thanks very much, it is the problem that I was not downloading the .h5 file correctly.

**Comment by billcsu** [comment]
Additional question related to this one:  whether py4vas can be installed on Windows anaconda enviroment.  I've tried, but failed when getting requirements to build wheel.
![image](https://github.com/vasp-dev/py4vasp/assets/133481966/b6ea260b-df98-473e-a4c8-7641b6618149)
