### ISSUE TITLE
Function of integration of DOS

### ISSUE THREAD

**Issue by billcsu** [vasp-dev/py4vasp#90]
Whether there is a function to integrate DOS in py4vasp, which will be very convenient to take a quick look at the contribution of certain atom or orbital.  Such as integration of Ni 3d in the range of (-2,0) eV to see its contribution to the occupied orbitals.

**Comment by martin-schlipf** [comment]
At the moment such a functionality is not available. What you should be able to to is something along these lines
~~~python
import numpy as np
from py4vasp import Calculation
calc = Calculation.from_path("folder_with_vaspout")
data = calc.dos.read("Ni(d)")
mask = np.logical_and(-2 < data["energies"], data["energies"] < 0)
step = data["energies"][1] - data["energies"][0]
int_dos_up = np.cumsum(data["Ni_d_up"][mask]) / step
int_dos_down = np.cumsum(data["Ni_d_down"][mask]) / step
~~~

**Comment by billcsu** [comment]
Thanks very much!!!

**Comment by billcsu** [comment]
> At the moment such a functionality is not available. What you should be able to to is something along these lines
> 
> ```python
> import numpy as np
> from py4vasp import Calculation
> calc = Calculation.from_path("folder_with_vaspout")
> data = calc.dos.read("Ni(d)")
> mask = np.logical_and(-2 < data["energies"], data["energies"] < 0)
> step = data["energies"][1] - data["energies"][0]
> int_dos_up = np.cumsum(data["Ni_d_up"][mask]) / step
> int_dos_down = np.cumsum(data["Ni_d_down"][mask]) / step
> ```

Thanks very much!!!  But I think maybe it is 
`int_dos_up = np.cumsum(data["Ni_d_up"][mask]) * step`

**Comment by martin-schlipf** [comment]
Yes, I think you are right
