### ISSUE TITLE
Why is there no magnetism

### ISSUE THREAD

**Issue by billcsu** [vasp-dev/py4vasp#91]
I've set the MAGMOM and ISPIN, why is there no magnetism information out
<img width="952" alt="image" src="https://github.com/vasp-dev/py4vasp/assets/133481966/54d7ab78-d8d5-4fea-bdbc-f30086cef235">

**Comment by martin-schlipf** [comment]
The magnetism, i.e. the site projected magnetic moments, are only available when you run with LORBIT = 10 or 11.
